Repository umbraco/Umbraco.UI, pull requests merged in 2022-03, with the labels that each got.

#148 Feature/chromatic
  .github/workflows/chromatic.yml
  .github/workflows/codeql-analysis.yml
  package-lock.json
  package.json
  packages/uui-avatar-group/lib/uui-avatar-group.story.ts
  packages/uui-avatar/lib/uui-avatar.story.ts
  packages/uui-card-media/lib/uui-card-media.story.ts
  packages/uui-loader-bar/lib/uui-loader-bar.story.ts
  packages/uui-loader-circle/lib/uui-loader-circle.story.ts
  packages/uui-loader/lib/uui-loader.story.ts
  storyhelpers/UmbracoWordGenerator.ts
Labels: documentation, enhancement

#146 Feature/uui-popover-refactor
  .github/workflows/chromatic.yml
  .storybook/preview-head.html
  package-lock.json
  package.json
  packages/uui-popover/README.md
  packages/uui-popover/lib/UUIPopoverEvent.ts
  packages/uui-popover/lib/index.ts
  packages/uui-popover/lib/uui-popover.element.ts
  packages/uui-popover/lib/uui-popover.story.ts
  packages/uui-popover/lib/uui-popover.test.ts
  packages/uui-popover/package.json
  packages/uui-popover/rollup.config.js
  packages/uui-popover/tsconfig.json
  packages/uui/lib/index.ts
Labels: enhancement, feature

#21 Created Package-Card
  src/components/uui-package-card/uui-package-card.element.ts
  src/components/uui-package-card/uui-package-card.story.ts
Labels: help wanted, feature

#153 Tidies up docs for Avatar & Avatar Group
  packages/uui-avatar-group/lib/uui-avatar-group.story.ts
  packages/uui-avatar/lib/uui-avatar.story.ts
Labels: documentation

#118 uui-symbol-lock
  package-lock.json
  packages/uui-symbol-lock/README.md
  packages/uui-symbol-lock/lib/index.ts
  packages/uui-symbol-lock/lib/uui-symbol-lock.element.ts
  packages/uui-symbol-lock/lib/uui-symbol-lock.story.ts
  packages/uui-symbol-lock/lib/uui-symbol-lock.test.ts
  packages/uui-symbol-lock/package.json
  packages/uui-symbol-lock/rollup.config.js
  packages/uui-symbol-lock/tsconfig.json
  packages/uui/lib/index.ts
  src/components/uui-lock-symbol/index.ts
  src/components/uui-lock-symbol/uui-lock-symbol.story.ts
Labels: feature

#157 fix: uui-toggle change adjacent sibling combinator to general sibling
  packages/uui-toggle/lib/uui-toggle.element.ts
Labels: enhancement

#162 Add playwright test runner
  .github/workflows/azure-static-web-apps-delightful-beach-055ecb503.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  package-lock.json
  package.json
  packages/uui-breadcrumbs/lib/uui-breadcrumbs.test.ts
  packages/uui-button/lib/uui-button.element.ts
  packages/uui-form-layout-item/lib/form.story.ts
  packages/uui-form-validation-message/lib/uui-form-validation-message.element.ts
  packages/uui-form-validation-message/lib/uui-form-validation-message.test.ts
  packages/uui-form/lib/uui-form.story.ts
  packages/uui-form/lib/uui-form.test.ts
  packages/uui-input/lib/uui-input-form-example.ts
  packages/uui-input/lib/uui-input.story.ts
  web-test-runner.config.mjs
Labels: enhancement

#166 Hide native input in Safari.
  packages/uui-boolean-input/lib/uui-boolean-input.element.ts
Labels: bug

#160 Feature/storybook slots documentation
  .storybook/preview.js
  packages/uui-avatar-group/lib/uui-avatar-group.element.ts
  packages/uui-avatar/lib/uui-avatar.element.ts
  packages/uui-avatar/lib/uui-avatar.story.ts
  packages/uui-badge/lib/uui-badge.element.ts
  packages/uui-badge/lib/uui-badge.story.ts
  packages/uui-base/lib/mixins/FormControlMixin.ts
  packages/uui-base/lib/mixins/LabelMixin.ts
  packages/uui-box/lib/uui-box.element.ts
  packages/uui-box/lib/uui-box.story.ts
  packages/uui-breadcrumbs/lib/uui-breadcrumb-item.element.ts
  packages/uui-breadcrumbs/lib/uui-breadcrumbs.element.ts
  packages/uui-button-group/lib/uui-button-group.element.ts
  packages/uui-card-content-node/lib/uui-card-content-node.element.ts
  packages/uui-card-content-node/lib/uui-card-content-node.story.ts
  packages/uui-card-media/lib/uui-card-media.element.ts
  packages/uui-card-user/lib/uui-card-user.element.ts
  packages/uui-checkbox/lib/uui-checkbox.element.ts
  packages/uui-dialog-layout/lib/uui-dialog-layout.element.ts
  packages/uui-dialog/lib/uui-dialog.element.ts
  packages/uui-form-layout-item/lib/uui-form-layout-item.element.ts
  packages/uui-form-validation-message/lib/uui-form-validation-message.element.ts
  packages/uui-keyboard-shortcut/lib/uui-keyboard-shortcut.element.ts
  packages/uui-label/lib/uui-label.element.ts
  packages/uui-label/lib/uui-label.story.ts
  packages/uui-menu-item/lib/uui-menu-item.element.ts
  packages/uui-popover/lib/uui-popover.element.ts
  packages/uui-popover/lib/uui-popover.story.ts
  packages/uui-radio/lib/uui-radio-group.element.ts
  packages/uui-radio/lib/uui-radio.element.ts
  packages/uui-radio/lib/uui-radio.story.ts
  packages/uui-ref-node/lib/uui-ref-node.element.ts
  packages/uui-ref-node/lib/uui-ref-node.story.ts
  packages/uui-scroll-container/lib/uui-scroll-container.element.ts
  packages/uui-scroll-container/lib/uui-scroll-container.story.ts
  packages/uui-table/lib/uui-table-cell.element.ts
  packages/uui-table/lib/uui-table-head.element.ts
  packages/uui-table/lib/uui-table.element.ts
  packages/uui-tabs/lib/uui-tab-group.element.ts
  packages/uui-tag/lib/uui-tag.element.ts
  packages/uui-tag/lib/uui-tag.story.ts
  packages/uui-toast-notification-container/lib/uui-toast-notification-container.element.ts
  packages/uui-toast-notification-layout/lib/uui-toast-notification-layout.element.ts
  packages/uui-toast-notification-layout/lib/uui-toast-notification-layout.story.ts
  packages/uui-toast-notification/lib/uui-toast-notification.element.ts
  packages/uui-toast-notification/lib/uui-toast-notification.story.ts
  packages/uui-toggle/lib/uui-toggle.element.ts
Labels: documentation

#172 Implement demandCustomElement for all packages
  package-lock.json
  packages/uui-avatar-group/package.json
  packages/uui-avatar-group/tsconfig.json
  packages/uui-button-group/package.json
  packages/uui-button-group/tsconfig.json
  packages/uui-button/lib/uui-button.element.ts
  packages/uui-button/package.json
  packages/uui-button/tsconfig.json
  packages/uui-card-content-node/lib/uui-card-content-node.element.ts
  packages/uui-card-media/lib/uui-card-media.element.ts
  packages/uui-card-user/lib/uui-card-user.element.ts
  packages/uui-checkbox/package.json
  packages/uui-checkbox/tsconfig.json
  packages/uui-form-layout-item/lib/uui-form-layout-item.element.ts
  packages/uui-form-layout-item/package.json
  packages/uui-form-layout-item/tsconfig.json
  packages/uui-input-lock/lib/uui-input-lock.element.ts
  packages/uui-input-lock/package.json
  packages/uui-input-lock/tsconfig.json
  packages/uui-input-password/lib/uui-input-password.element.ts
  packages/uui-menu-item/lib/uui-menu-item.element.ts
  packages/uui-menu-item/package.json
  packages/uui-menu-item/tsconfig.json
  packages/uui-pagination/lib/uui-pagination.element.ts
  packages/uui-ref-node/lib/uui-ref-node.element.ts
  packages/uui-toast-notification-layout/package.json
  packages/uui-toast-notification-layout/tsconfig.json
  packages/uui-toast-notification/lib/uui-toast-notification.element.ts
  packages/uui-toast-notification/package.json
  packages/uui-toast-notification/tsconfig.json
Labels: enhancement

#169 Loader colors
  package-lock.json
  packages/uui-button/lib/uui-button.element.ts
  packages/uui-button/lib/uui-button.story.ts
  packages/uui-css/lib/custom-properties/colors.css
  packages/uui-loader-bar/lib/uui-loader-bar.element.ts
  packages/uui-loader-bar/lib/uui-loader-bar.story.ts
  packages/uui-loader-circle/lib/uui-loader-circle.element.ts
  packages/uui-loader-circle/lib/uui-loader-circle.story.ts
  packages/uui-loader/lib/uui-loader.element.ts
  packages/uui-loader/lib/uui-loader.story.ts
Labels: feature

#174 ability to map validaty state from native input to a custom form control
  packages/uui-base/lib/mixins/FormControlMixin.ts
  packages/uui-form/lib/uui-form.story.ts
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-input/lib/uui-input.test.ts
Labels: feature

#180 Bugfix: Add missing uui-key element definition
  packages/uui-keyboard-shortcut/lib/uui-key.element.ts
  packages/uui-keyboard-shortcut/lib/uui-keyboard-shortcut.test.ts
Labels: bug
