Repository umbraco/Umbraco.UI, pull requests merged in 2022-08, with the labels that each got.

#288 Form submits when clicking enter
  packages/uui-base/lib/mixins/FormControlMixin.ts
  packages/uui-boolean-input/lib/uui-boolean-input.element.ts
  packages/uui-boolean-input/lib/uui-boolean-input.test.ts
  packages/uui-form/lib/uui-form.element.ts
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-input/lib/uui-input.test.ts
  packages/uui-radio/lib/uui-radio-group.element.ts
  packages/uui-radio/lib/uui-radio-group.test.ts
  packages/uui-slider/lib/uui-slider.element.ts
  packages/uui-slider/lib/uui-slider.test.ts
Labels: enhancement

#289 Add labels to fix accessibility warnings
  packages/uui-base/lib/mixins/LabelMixin.ts
  packages/uui-form-layout-item/lib/uui-form-layout-item.story.ts
  packages/uui-input/lib/uui-input.element.ts
Labels: documentation

#292 Bugfix/dispatching of events twice
  packages/uui-base/lib/events/UUIEvent.ts
  packages/uui-boolean-input/lib/uui-boolean-input.element.ts
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-radio/lib/uui-radio-group.element.ts
  packages/uui-radio/lib/uui-radio.element.ts
  packages/uui-select/lib/uui-select.element.ts
  packages/uui-slider/lib/uui-slider.element.ts
  packages/uui-textarea/lib/uui-textarea.element.ts
Labels: bug

#293 V1/feature/a11y tests
  package-lock.json
  package.json
  packages/uui-button/lib/uui-button.test.ts
  packages/uui-table/lib/uui-table.test.ts
  web-test-runner.config.mjs
Labels: enhancement, dependencies

#299 FIXES:#297 - Missing custom icon for reference nodes in Storybook
  packages/uui-ref-node-data-type/lib/uui-ref-node-data-type.story.ts
  packages/uui-ref-node-document-type/lib/uui-ref-node-document-type.story.ts
  packages/uui-ref-node-form/lib/uui-ref-node-form.story.ts
  packages/uui-ref-node-member/lib/uui-ref-node-member.story.ts
  packages/uui-ref-node-package/lib/uui-ref-node-package.story.ts
  packages/uui-ref-node-user/lib/uui-ref-node-user.story.ts
  packages/uui-ref-node/lib/uui-ref-node.story.ts
Labels: documentation

#300 FIXES:#295 - Missing media card disabled footer and action button backgrounds
  packages/uui-card-media/lib/uui-card-media.element.ts
  packages/uui-card-media/lib/uui-card-media.story.ts
Labels: bug

#298 Bugfix - UUI Radiobutton Circle is malformed on multiple lines
  packages/uui-radio/lib/uui-radio.element.ts
  packages/uui-radio/lib/uui-radio.story.ts
Labels: bug

#311 fix focus issues on uui-combobox
  packages/uui-combobox/lib/uui-combobox.element.ts
  packages/uui-scroll-container/lib/uui-scroll-container.element.ts
Labels: bug
