Repository umbraco/Umbraco.UI, pull requests merged in 2022-11, with the labels that each got.

#351 [Input lock] Bump opacity a bit, to pass color contrast accessibility check
  packages/uui-input-lock/lib/uui-input-lock.element.ts
Labels: hacktoberfest-accepted

#354 fix: Add cd to installation instruction before npm install
  README.md
Labels: documentation, community/pr, hacktoberfest-accepted

#363 Case insensitivity when using combobox-avatar
  packages/uui-combobox/lib/uui-combobox.story.ts
Labels: bug, community/pr, hacktoberfest-accepted

#364 Have pagination render update
  packages/uui-pagination/lib/uui-pagination.element.ts
Labels: bug, community/pr, hacktoberfest-accepted

#362 uui-input change aling-items to stretch
  packages/uui-input/lib/uui-input.element.ts
Labels: bug
