Repository umbraco/Umbraco.UI, pull requests merged in 2022-09, with the labels that each got.

#331 build(deps-dev): update typescript to 4.8.3
  package-lock.json
  package.json
  tsconfig.json
Labels: dependencies

#327 uui-combobox: optimizations for small resolutions
  packages/uui-combobox/lib/uui-combobox.element.ts
Labels: bug

#335 Fix typo in Button Looks and Colors Story
  packages/uui-button/lib/uui-button.story.ts
Labels: community/pr

#339 uui-input-password sets spellcheck to false
  packages/uui-input-password/lib/uui-input-password.element.ts
Labels: enhancement

#325 Feature/range slider two handles
  package-lock.json
  packages/uui-range-slider/README.md
  packages/uui-range-slider/lib/UUIRangeSliderEvent.ts
  packages/uui-range-slider/lib/index.ts
  packages/uui-range-slider/lib/uui-range-slider.element.ts
  packages/uui-range-slider/lib/uui-range-slider.story.ts
  packages/uui-range-slider/lib/uui-range-slider.test.ts
  packages/uui-range-slider/package.json
  packages/uui-range-slider/rollup.config.js
  packages/uui-range-slider/tsconfig.json
  packages/uui/lib/index.ts
Labels: feature
