Repository umbraco/Umbraco.UI, pull requests merged in 2022-04, with the labels that each got.

#188 added ignoreChanges
  lerna.json
Labels: enhancement

#187 fix: add missing reference to uui-input-lock for uui
  packages/uui/package.json
Labels: bug

#189 UUI-Box: Removing local definition of --uui-box-default-padding
  packages/uui-box/lib/uui-box.element.ts
  packages/uui-box/lib/uui-box.test.ts
Labels: bug

#196 change _onInput method from private to protected
  packages/uui-input/lib/uui-input.element.ts
Labels: feature

#186 Added Combobox Component
  package-lock.json
  packages/uui-base/lib/events/UUISelectableEvent.ts
  packages/uui-base/lib/mixins/SelectableMixin.ts
  packages/uui-button/lib/uui-button.element.ts
  packages/uui-combobox-list/README.md
  packages/uui-combobox-list/lib/UUIComboboxListEvent.ts
  packages/uui-combobox-list/lib/index.ts
  packages/uui-combobox-list/lib/uui-combobox-list-option.element.ts
  packages/uui-combobox-list/lib/uui-combobox-list.element.ts
  packages/uui-combobox-list/lib/uui-combobox-list.story.ts
  packages/uui-combobox-list/lib/uui-combobox-list.test.ts
  packages/uui-combobox-list/package.json
  packages/uui-combobox-list/rollup.config.js
  packages/uui-combobox-list/tsconfig.json
  packages/uui-combobox/README.md
  packages/uui-combobox/lib/UUIComboboxEvent.ts
  packages/uui-combobox/lib/index.ts
  packages/uui-combobox/lib/uui-combobox-async-example.ts
  packages/uui-combobox/lib/uui-combobox.element.ts
  packages/uui-combobox/lib/uui-combobox.story.ts
  packages/uui-combobox/lib/uui-combobox.test.ts
  packages/uui-combobox/package.json
  packages/uui-combobox/rollup.config.js
  packages/uui-combobox/tsconfig.json
  packages/uui-form/lib/uui-form.story.ts
  packages/uui-input/lib/UUIInputEvent.ts
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-input/lib/uui-input.test.ts
  packages/uui-popover/lib/uui-popover.element.ts
  packages/uui/lib/index.ts
  packages/uui/package.json
  packages/uui/tsconfig.json
  storyhelpers/RegionsAndCountries.ts
Labels: enhancement, feature
