Repository umbraco/Umbraco.UI, pull requests merged in 2023-07, with the labels that each got.

#522 select mode for highlight
  packages/uui-base/lib/mixins/SelectableMixin.ts
  packages/uui-menu-item/lib/uui-menu-item.element.ts
  packages/uui-menu-item/lib/uui-menu-item.story.ts
  packages/uui-menu-item/lib/uui-menu-item.test.ts
Labels: enhancement

#525 Typo in story for uui-loader-bar
  packages/uui-loader-bar/lib/uui-loader-bar.story.ts
Labels: documentation, community/pr

#519 docs(storybook): add icon slot example for uui-tab element (#356)
  packages/uui-tabs/lib/uui-tabs.story.ts
Labels: documentation, community/pr

#521 uui-box: add a property to control the headline variant
  .gitignore
  .vscode/settings.json
  packages/uui-base/lib/types/InterfaceHeading.ts
  packages/uui-base/lib/types/index.ts
  packages/uui-box/README.md
  packages/uui-box/lib/uui-box.element.ts
  packages/uui-box/lib/uui-box.story.ts
  packages/uui-box/lib/uui-box.test.ts
  typings.d.ts
Labels: feature, community/pr

#538 Upgrade storybook version
  package-lock.json
  package.json
Labels: documentation, community/pr
