Repository umbraco/Umbraco.UI, pull requests merged in 2023-10, with the labels that each got.

#592 update storybook version to 7.4.5
  package-lock.json
  package.json
Labels: dependencies

#597 uui-textarea: font size and auto-height optimisations
  packages/uui-textarea/lib/uui-textarea.element.ts
Labels: enhancement

#607 Remove whitespace before semicolon when generating new package
  templates/plop-templates/component.ts.hbs
Labels: internal, community/pr, hacktoberfest/contrib-2023

#591 Disable elements when color picker is disabled
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-picker/lib/uui-color-picker.story.ts
  packages/uui-color-swatch/lib/uui-color-swatch.element.ts
  packages/uui-color-swatches/lib/uui-color-swatches.element.ts
Labels: hacktoberfest/contrib-2023

#609 Add support for GitHub Codespaces
  .devcontainer/devcontainer.json
  .vscode/settings.json
  .vscode/tasks.json
Labels: internal, community/pr, hacktoberfest/contrib-2023

#612 Set aria-hidden if no label has been set
  packages/uui-icon/lib/uui-icon.element.ts
Labels: enhancement, community/pr, hacktoberfest/contrib-2023

#610 Add HSV as accepted color format
  packages/uui-color-picker/lib/uui-color-picker.element.ts
Labels: enhancement, community/pr, hacktoberfest/contrib-2023

#593 Visually hidden component
  package-lock.json
  packages/uui-visually-hidden/README.md
  packages/uui-visually-hidden/lib/index.ts
  packages/uui-visually-hidden/lib/uui-visually-hidden.element.ts
  packages/uui-visually-hidden/lib/uui-visually-hidden.story.ts
  packages/uui-visually-hidden/lib/uui-visually-hidden.test.ts
  packages/uui-visually-hidden/package.json
  packages/uui-visually-hidden/rollup.config.js
  packages/uui-visually-hidden/tsconfig.json
  packages/uui/lib/index.ts
Labels: feature, community/pr, hacktoberfest/contrib-2023

#537 Specific control types in storybook controls
  packages/uui-color-picker/lib/uui-color-picker.story.ts
  packages/uui-color-slider/lib/uui-color-slider.story.ts
Labels: documentation, community/pr, hacktoberfest/contrib-2023

#630 Added missing bracket to uui-radio story
  packages/uui-radio/lib/uui-radio.story.ts
Labels: documentation, community/pr, hacktoberfest/contrib-2023

#631 Updated contributing link in pull request template
  .github/pull_request_template.md
Labels: documentation, community/pr, hacktoberfest/contrib-2023

#635 Accept input type search
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-input/lib/uui-input.story.ts
Labels: enhancement, community/pr, hacktoberfest/contrib-2023
