Repository umbraco/Umbraco.UI, pull requests merged in 2023-11, with the labels that each got.

#643 build: bump support to nodejs 20.x
  .github/workflows/chromatic.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  .nvmrc
  package-lock.json
  package.json
Labels: ignore-for-release

#644 build(deps): bump storybook to 7.5.2
  package-lock.json
  package.json
Labels: dependencies, javascript

#651 Corrected icons, so they are done in the same way as previous icons
  packages/uui-icon-registry-essential/lib/svgs/iconAdd.ts
  packages/uui-icon-registry-essential/lib/svgs/iconAlert.ts
  packages/uui-icon-registry-essential/lib/svgs/iconAttachment.ts
  packages/uui-icon-registry-essential/lib/svgs/iconCalendar.ts
  packages/uui-icon-registry-essential/lib/svgs/iconCheck.ts
  packages/uui-icon-registry-essential/lib/svgs/iconClipboard.ts
  packages/uui-icon-registry-essential/lib/svgs/iconCode.ts
  packages/uui-icon-registry-essential/lib/svgs/iconColorPicker.ts
  packages/uui-icon-registry-essential/lib/svgs/iconCopy.ts
  packages/uui-icon-registry-essential/lib/svgs/iconDelete.ts
  packages/uui-icon-registry-essential/lib/svgs/iconDocument.ts
  packages/uui-icon-registry-essential/lib/svgs/iconDownload.ts
  packages/uui-icon-registry-essential/lib/svgs/iconEdit.ts
  packages/uui-icon-registry-essential/lib/svgs/iconFavorite.ts
  packages/uui-icon-registry-essential/lib/svgs/iconFolder.ts
  packages/uui-icon-registry-essential/lib/svgs/iconForbidden.ts
  packages/uui-icon-registry-essential/lib/svgs/iconInfo.ts
  packages/uui-icon-registry-essential/lib/svgs/iconLink.ts
  packages/uui-icon-registry-essential/lib/svgs/iconLock.ts
  packages/uui-icon-registry-essential/lib/svgs/iconPause.ts
  packages/uui-icon-registry-essential/lib/svgs/iconPicture.ts
  packages/uui-icon-registry-essential/lib/svgs/iconPlay.ts
  packages/uui-icon-registry-essential/lib/svgs/iconRemove.ts
  packages/uui-icon-registry-essential/lib/svgs/iconSearch.ts
  packages/uui-icon-registry-essential/lib/svgs/iconSee.ts
  packages/uui-icon-registry-essential/lib/svgs/iconSettings.ts
  packages/uui-icon-registry-essential/lib/svgs/iconSubtract.ts
  packages/uui-icon-registry-essential/lib/svgs/iconSync.ts
  packages/uui-icon-registry-essential/lib/svgs/iconUnlock.ts
  packages/uui-icon-registry-essential/lib/svgs/iconUnsee.ts
  packages/uui-icon-registry-essential/lib/svgs/iconWand.ts
  packages/uui-icon-registry-essential/lib/svgs/iconWrong.ts
Labels: ignore-for-release

#649 uui-swatch: ability to overwrite displayed color with a css custom prop
  .vscode/settings.json
  packages/uui-color-swatch/lib/uui-color-swatch.element.ts
  packages/uui-color-swatch/lib/uui-color-swatch.story.ts
  packages/uui-color-swatches/lib/uui-color-swatches.element.ts
  packages/uui-color-swatches/lib/uui-color-swatches.story.ts
Labels: enhancement

#624 Don't hide placeholder text on focus
  packages/uui-input/lib/uui-input.element.ts
Labels: bug, community/pr, hacktoberfest-accepted, hacktoberfest/contrib-2023

#648 correct green colors for A11Y
  packages/uui-css/lib/custom-properties/colors.css
  packages/uui-css/lib/custom-properties/palette.css
Labels: accessibility

#628 Feature/popover container firefox polyfill
  packages/uui-base/lib/utils/findAncestorByAttributeValue.ts
  packages/uui-popover-container/lib/uui-popover-container.element.ts
  packages/uui-popover-container/lib/uui-popover-container.mdx
  packages/uui-popover-container/lib/uui-popover-container.story.ts
  packages/uui-popover-container/lib/uui-popover-polyfill.ts
  packages/uui-popover/lib/uui-popover.element.ts
  packages/uui-popover/lib/uui-popover.mdx
Labels: enhancement

#662 fix: uui-dropzone should set the 'accept' attribute
  packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
Labels: bug

#664 uui-popover-container: set popover attribute automatically
  packages/uui-popover-container/lib/uui-popover-container.element.ts
  packages/uui-popover-container/lib/uui-popover-container.mdx
Labels: enhancement

#663 uui-popover-container: disable the focusout close listener
  packages/uui-popover-container/lib/uui-popover-container.element.ts
Labels: bug

#665 uui-menu-item: add flatten css var to hide chevron column
  packages/uui-menu-item/lib/uui-menu-item.element.ts
  packages/uui-menu-item/lib/uui-menu-item.story.ts
Labels: enhancement
