Repository umbraco/Umbraco.UI, pull requests merged in 2023-01, with the labels that each got.

#389 Disabled input not displayed properly in Safari
  packages/uui-input/lib/uui-input.element.ts
Labels: bug

#402 uui-card-media does not render images correctly
  packages/uui-card-media/lib/uui-card-media.element.ts
Labels: bug

#280 Color picker
  README.md
  package-lock.json
  package.json
  packages/rollup-package.config.mjs
  packages/uui-base/lib/utils/drag.ts
  packages/uui-base/lib/utils/index.ts
  packages/uui-base/lib/utils/math.ts
  packages/uui-color-area/README.md
  packages/uui-color-area/lib/UUIColorAreaEvents.ts
  packages/uui-color-area/lib/index.ts
  packages/uui-color-area/lib/uui-color-area.element.ts
  packages/uui-color-area/lib/uui-color-area.story.ts
  packages/uui-color-area/lib/uui-color-area.test.ts
  packages/uui-color-area/package.json
  packages/uui-color-area/rollup.config.js
  packages/uui-color-area/tsconfig.json
  packages/uui-color-picker/README.md
  packages/uui-color-picker/lib/UUIColorPickerEvents.ts
  packages/uui-color-picker/lib/index.ts
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-picker/lib/uui-color-picker.story.ts
  packages/uui-color-picker/lib/uui-color-picker.test.ts
  packages/uui-color-picker/package.json
  packages/uui-color-picker/rollup.config.js
  packages/uui-color-picker/tsconfig.json
  packages/uui-color-slider/README.md
  packages/uui-color-slider/lib/UUIColorSliderEvents.ts
  packages/uui-color-slider/lib/index.ts
  packages/uui-color-slider/lib/uui-color-slider.element.ts
  packages/uui-color-slider/lib/uui-color-slider.story.ts
  packages/uui-color-slider/lib/uui-color-slider.test.ts
  packages/uui-color-slider/package.json
  packages/uui-color-slider/rollup.config.js
  packages/uui-color-slider/tsconfig.json
  packages/uui-color-swatch/README.md
  packages/uui-color-swatch/lib/index.ts
  packages/uui-color-swatch/lib/uui-color-swatch.element.ts
  packages/uui-color-swatch/lib/uui-color-swatch.story.ts
  packages/uui-color-swatch/lib/uui-color-swatch.test.ts
  packages/uui-color-swatch/package.json
  packages/uui-color-swatch/rollup.config.js
  packages/uui-color-swatch/tsconfig.json
  packages/uui-color-swatches/README.md
  packages/uui-color-swatches/lib/UUIColorSwatchesEvents.ts
  packages/uui-color-swatches/lib/index.ts
  packages/uui-color-swatches/lib/uui-color-swatches.element.ts
  packages/uui-color-swatches/lib/uui-color-swatches.story.ts
  packages/uui-color-swatches/lib/uui-color-swatches.test.ts
  packages/uui-color-swatches/package.json
  packages/uui-color-swatches/rollup.config.js
  packages/uui-color-swatches/tsconfig.json
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-popover/lib/uui-popover.element.ts
  packages/uui/lib/index.ts
  packages/uui/package.json
  packages/uui/tsconfig.json
Labels: feature, community/pr

#395 uui-input-file => Only show add button when multiple or no file selected
  packages/uui-input-file/lib/uui-input-file.element.ts
Labels: enhancement

#408 fix: Add whitespace when appending/prepending icon in uui-input
  packages/uui-icon/lib/uui-icon.element.ts
  packages/uui-input/lib/uui-input.story.ts
Labels: bug

#411 update dependencies
  package-lock.json
  package.json
Labels: dependencies

#410 Fix background color in uui-textarea
  packages/uui-textarea/lib/uui-textarea.element.ts
  packages/uui-textarea/lib/uui-textarea.story.ts
Labels: bug
