Repository umbraco/Umbraco.UI, pull requests merged in 2023-05, with the labels that each got.

#477 fix: uui-file-dropzone does not export its event classes
  packages/uui-file-dropzone/lib/index.ts
Labels: bug

#478 fix: uui-file-dropzone does not follow the inferred interface for dropped files
  packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
  packages/uui-file-dropzone/lib/uui-file-dropzone.story.ts
Labels: bug

#476 feat: change events to align with native browser behavior
  docs/EVENTS.md
  packages/uui-base/lib/events/UUIEvent.ts
  packages/uui-base/lib/events/UUISelectableEvent.ts
  packages/uui-base/lib/mixins/SelectableMixin.ts
  packages/uui-boolean-input/lib/UUIBooleanInputEvent.ts
  packages/uui-boolean-input/lib/uui-boolean-input.test.ts
  packages/uui-button-inline-create/lib/UUIButtonInlineCreateEvent.ts
  packages/uui-color-area/lib/UUIColorAreaEvent.ts
  packages/uui-color-area/lib/index.ts
  packages/uui-color-area/lib/uui-color-area.element.ts
  packages/uui-color-picker/lib/UUIColorPickerEvent.ts
  packages/uui-color-picker/lib/index.ts
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-slider/lib/UUIColorSliderEvent.ts
  packages/uui-color-slider/lib/index.ts
  packages/uui-color-slider/lib/uui-color-slider.element.ts
  packages/uui-color-swatches/lib/UUIColorSwatchesEvent.ts
  packages/uui-color-swatches/lib/index.ts
  packages/uui-color-swatches/lib/uui-color-swatches.element.ts
  packages/uui-combobox-list/lib/UUIComboboxListEvent.ts
  packages/uui-combobox-list/lib/uui-combobox-list.element.ts
  packages/uui-combobox/lib/UUIComboboxEvent.ts
  packages/uui-combobox/lib/uui-combobox.element.ts
  packages/uui-file-dropzone/lib/UUIFileDropzoneEvent.ts
  packages/uui-file-dropzone/lib/index.ts
  packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
  packages/uui-file-dropzone/lib/uui-file-dropzone.story.ts
  packages/uui-form/lib/uui-form.story.ts
  packages/uui-icon/lib/UUIIconRequestEvent.ts
  packages/uui-input-file/lib/uui-input-file.element.ts
  packages/uui-input/lib/UUIInputEvent.ts
  packages/uui-input/lib/uui-input.test.ts
  packages/uui-menu-item/lib/uui-menu-item.element.ts
  packages/uui-menu-item/lib/uui-menu-item.test.ts
  packages/uui-pagination/lib/UUIPaginationEvent.ts
  packages/uui-popover/lib/uui-popover.element.ts
  packages/uui-radio/lib/UUIRadioEvent.ts
  packages/uui-radio/lib/UUIRadioGroupEvent.ts
  packages/uui-radio/lib/uui-radio-group.element.ts
  packages/uui-range-slider/lib/UUIRangeSliderEvent.ts
  packages/uui-select/lib/UUISelectEvent.ts
  packages/uui-slider/lib/UUISliderEvent.ts
  packages/uui-slider/lib/index.ts
  packages/uui-slider/lib/uui-slider.element.ts
  packages/uui-slider/lib/uui-slider.test.ts
  packages/uui-tabs/lib/uui-tab-group.element.ts
  packages/uui-textarea/lib/UUITextareaEvent.ts
Labels: feature, notable

#484 feat: add missing native attributes to uui-input and uui-textarea
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-input/lib/uui-input.story.ts
  packages/uui-textarea/lib/uui-textarea.element.ts
  packages/uui-textarea/lib/uui-textarea.story.ts
Labels: enhancement

#486 Fix dragging in color area and sync value
  packages/uui-color-area/lib/uui-color-area.element.ts
Labels: bug

#488 Update story for color swatches
  packages/uui-color-swatches/lib/uui-color-swatches.story.ts
Labels: documentation

#500 docs: storybook color props
  packages/uui-color-area/lib/uui-color-area.story.ts
  packages/uui-color-picker/lib/uui-color-picker.story.ts
  packages/uui-color-slider/lib/uui-color-slider.story.ts
  packages/uui-color-swatch/lib/uui-color-swatch.element.ts
  packages/uui-color-swatch/lib/uui-color-swatch.story.ts
  packages/uui-color-swatches/lib/uui-color-swatches.element.ts
  packages/uui-color-swatches/lib/uui-color-swatches.story.ts
Labels: documentation
