Repository umbraco/Umbraco.UI, pull requests merged in 2023-03, with the labels that each got.

#434 add disabled property to uui-combobox
  packages/uui-combobox/lib/uui-combobox.element.ts
  packages/uui-combobox/lib/uui-combobox.story.ts
  packages/uui-combobox/lib/uui-combobox.test.ts
  packages/uui/tsconfig.json
Labels: feature

#441 uui-popover: added css custom property to overwrite z-index
  packages/uui-popover/lib/uui-popover.element.ts
Labels: feature

#427 uui-color-swatches: color swatches changes form when showLabel is true
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-swatch/lib/uui-color-swatch.element.ts
  packages/uui-color-swatch/lib/uui-color-swatch.story.ts
  packages/uui-color-swatches/lib/uui-color-swatches.element.ts
Labels: feature

#444 Modals - add size property to sidebar
  packages/uui-modal/lib/uui-modal-sidebar.element.ts
Labels: bug

#448 scroll container is now auto scroll and has an enforce scroll option
  packages/uui-scroll-container/lib/uui-scroll-container.element.ts
  packages/uui-scroll-container/lib/uui-scroll-container.story.ts
  packages/uui-scroll-container/lib/uui-scroll-container.test.ts
Labels: enhancement

#449 Fix so uui-ref-list border fits within the given space.
  packages/uui-ref-list/lib/uui-ref-list.element.ts
Labels: bug

#436 Bugfix/uui range slider overhaul
  .github/workflows/azure-static-web-apps-delightful-beach-055ecb503.yml
  .github/workflows/chromatic.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  .nvmrc
  packages/uui-range-slider/lib/uui-range-slider.element.ts
  packages/uui-range-slider/lib/uui-range-slider.story.ts
  packages/uui-range-slider/lib/uui-range-slider.test.ts
Labels: bug
