Repository umbraco/Umbraco.UI, pull requests merged in 2024-01, with the labels that each got.

#703 fix: direct imports are not allowed
  packages/uui-card-media/lib/uui-card-media.element.ts
  packages/uui-combobox/lib/uui-combobox.element.ts
  packages/uui-tabs/lib/uui-tab-group.element.ts
Labels: bug

#714 Ref Element: Change border attribute to standalone
  packages/uui-ref-node-data-type/lib/uui-ref-node-data-type.story.ts
  packages/uui-ref-node-document-type/lib/uui-ref-node-document-type.story.ts
  packages/uui-ref-node-form/lib/uui-ref-node-form.story.ts
  packages/uui-ref-node-member/lib/uui-ref-node-member.story.ts
  packages/uui-ref-node-package/lib/uui-ref-node-package.story.ts
  packages/uui-ref-node-user/lib/uui-ref-node-user.story.ts
  packages/uui-ref-node/lib/uui-ref-node.story.ts
  packages/uui-ref/lib/uui-ref.element.ts
Labels: breaking

#713 Bugfix/popover container scroll event
  packages/uui-popover-container/lib/uui-popover-container.element.ts
  packages/uui-popover-container/lib/uui-popover-container.story.ts
Labels: bug

#717 Ref: Use css var for text
  packages/uui-ref/lib/uui-ref.element.ts
Labels: bug

#715 feat: uui-ref-node should have href and target properties
  packages/uui-ref-node/lib/uui-ref-node.element.ts
  packages/uui-ref-node/lib/uui-ref-node.story.ts
Labels: enhancement

#712 uui-tab-group does not support having a gap between tabs
  packages/uui-tabs/lib/uui-tab-group.element.ts
  packages/uui-tabs/lib/uui-tab.element.ts
  packages/uui-tabs/lib/uui-tabs.story.ts
Labels: enhancement

#716 Prefix interface types with UUI
  packages/uui-badge/lib/uui-badge.element.ts
  packages/uui-base/lib/types/InterfaceColor.ts
  packages/uui-base/lib/types/InterfaceHeading.ts
  packages/uui-base/lib/types/InterfaceLook.ts
  packages/uui-box/lib/uui-box.element.ts
  packages/uui-box/lib/uui-box.test.ts
  packages/uui-button/lib/uui-button.element.ts
  packages/uui-button/lib/uui-button.test.ts
  packages/uui-tag/lib/uui-tag.element.ts
Labels: enhancement, breaking

#720 Inline-button-create: Add href
  packages/uui-button-inline-create/lib/uui-button-inline-create.element.ts
  packages/uui-button-inline-create/lib/uui-button-inline-create.story.ts
Labels: enhancement

#702 Fix modal close animation
  packages/uui-modal/lib/uui-modal-container.ts
  packages/uui-modal/lib/uui-modal-sidebar.element.ts
  packages/uui-modal/lib/uui-modal.element.ts
Labels: bug

#722 set display to block on uui-tab-group
  packages/uui-tabs/lib/uui-tab-group.element.ts
Labels: bug
