Repository umbraco/Umbraco.UI, pull requests merged in 2024-10, with the labels that each got.

#931 Bugfix: UUIFormControlMixinClass: Dont call setAttribute in the constructor
  packages/uui-base/lib/mixins/FormControlMixin.ts
Labels: bug

#932 Feat: Readonly state for uui-color-swatches
  packages/uui-color-swatches/lib/uui-color-swatches.element.ts
  packages/uui-color-swatches/lib/uui-color-swatches.story.ts
Labels: enhancement, community/pr

#933 Feat: Readonly state for uui-color-picker
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-picker/lib/uui-color-picker.story.ts
Labels: enhancement, community/pr, hacktoberfest-accepted, hacktoberfest/contrib-2024

#919 Ensure track step dots are in center on track
  packages/uui-range-slider/lib/uui-range-slider.element.ts
Labels: bug, community/pr
