Repository umbraco/Umbraco.UI, pull requests merged in 2024-02, with the labels that each got.

#727 Fix incorrect add icon
  packages/uui-icon-registry-essential/lib/svgs/iconAdd.ts
Labels: bug

#726 fix(uui-tab-group): async tabs are not calculated correctly and have memory leaks
  packages/uui-tabs/lib/uui-tab-group.element.ts
  packages/uui-tabs/lib/uui-tabs.story.ts
Labels: bug

#536 Don't update saturation based on parsed color
  packages/uui-color-area/lib/uui-color-area.element.ts
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-slider/lib/uui-color-slider.element.ts
Labels: bug, community/pr, hacktoberfest/contrib-2023

#729 Fix link to issue tracker
  README.md
Labels: documentation

#730 fix(uui-tab-group): layout is causing issues due to missing `display: flex`
  packages/uui-tabs/lib/uui-tab-group.element.ts
  packages/uui-tabs/lib/uui-tabs.story.ts
  packages/uui-tabs/lib/uui-tabs.test.ts
Labels: bug
