Repository umbraco/Umbraco.UI, pull requests merged in 2024-07, with the labels that each got.

#835 fix(uui-form-validation-message): default renderer does not support raw HTML
  packages/uui-form-validation-message/lib/uui-form-validation-message.element.ts
Labels: bug

#834 docs(uui-card-block-type): add descriptions for slots
  packages/uui-card-block-type/lib/uui-card-block-type.element.ts
Labels: documentation

#826 bug: Prevent UUIToggle from shrinking when the label contains a long string
  packages/uui-toggle/lib/uui-toggle.element.ts
Labels: bug

#814 feat: add `rel` property to relevant elements to override default behavior
  packages/uui-button-inline-create/lib/uui-button-inline-create.element.ts
  packages/uui-button/lib/uui-button.element.ts
  packages/uui-button/lib/uui-button.story.ts
  packages/uui-button/lib/uui-button.test.ts
  packages/uui-card-block-type/lib/uui-card-block-type.element.ts
  packages/uui-card-block-type/lib/uui-card-block-type.story.ts
  packages/uui-card-content-node/lib/uui-card-content-node.element.ts
  packages/uui-card-content-node/lib/uui-card-content-node.story.ts
  packages/uui-card-media/lib/uui-card-media.element.ts
  packages/uui-card-media/lib/uui-card-media.story.ts
  packages/uui-card-user/lib/uui-card-user.element.ts
  packages/uui-card-user/lib/uui-card-user.story.ts
  packages/uui-card/lib/uui-card.element.ts
  packages/uui-menu-item/lib/uui-menu-item.element.ts
  packages/uui-menu-item/lib/uui-menu-item.story.ts
  packages/uui-menu-item/lib/uui-menu-item.test.ts
  packages/uui-ref-node/lib/uui-ref-node.element.ts
  packages/uui-ref-node/lib/uui-ref-node.story.ts
  packages/uui-tabs/lib/uui-tab.element.ts
  packages/uui-tabs/lib/uui-tab.test.ts
Labels: feature

#836 fix(uui-input-lock): the `UUIInputLockEvent` is not exported
  packages/uui-input-lock/lib/index.ts
Labels: bug

#841 feat: dropzone should support folder upload
  packages/uui-file-dropzone/lib/UUIFileDropzoneEvent.ts
  packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
  packages/uui-file-dropzone/lib/uui-file-dropzone.test.ts
Labels: feature

#842 feat(uui-color-picker): allow the value to be empty
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-picker/lib/uui-color-picker.story.ts
Labels: feature

#847 fix: revert the function to calculate if a default slot is empty
  packages/uui-base/lib/mixins/LabelMixin.ts
  packages/uui-button/lib/uui-button.story.ts
  packages/uui-button/lib/uui-button.test.ts
  packages/uui-toggle/lib/uui-toggle.story.ts
Labels: bug

#852 Update typo in story for radiobutton
  packages/uui-radio/lib/uui-radio.story.ts
Labels: documentation, community/pr

#856 Indeterminate state for boolean input and checkbox
  packages/uui-boolean-input/lib/uui-boolean-input.element.ts
  packages/uui-checkbox/lib/uui-checkbox.element.ts
  packages/uui-checkbox/lib/uui-checkbox.story.ts
Labels: feature, community/pr

#857 Consistent cursor style for checkbox and radiobutton
  packages/uui-boolean-input/lib/uui-boolean-input.element.ts
  packages/uui-checkbox/lib/uui-checkbox.story.ts
  packages/uui-checkbox/lib/uui-checkbox.test.ts
  packages/uui-radio/lib/uui-radio-group.test.ts
  packages/uui-radio/lib/uui-radio.element.ts
  packages/uui-radio/lib/uui-radio.story.ts
  packages/uui-toggle/lib/uui-toggle.story.ts
  packages/uui-toggle/lib/uui-toggle.test.ts
Labels: bug, community/pr

#859 chore(uui-loader-bar): use the generic `clamp` function from `uui-base`
  packages/uui-loader-bar/lib/uui-loader-bar.element.ts
Labels: feature

#866 fix(uui-textarea): add danger border if the element is invalid
  packages/uui-textarea/lib/uui-textarea.element.ts
Labels: bug

#858 feat(uui-popover-container): remove the Firefox popover polyfill
  .github/workflows/tests.yml
  package-lock.json
  package.json
  packages/uui-popover-container/lib/uui-popover-container.element.ts
  packages/uui-popover-container/lib/uui-popover-container.test.ts
  packages/uui-popover-container/lib/uui-popover-polyfill.ts
Labels: feature

#860 docs(uui-checkbox): Indeterminate checkbox story
  packages/uui-checkbox/lib/uui-checkbox-indeterminate.example.ts
  packages/uui-checkbox/lib/uui-checkbox.story.ts
Labels: documentation, community/pr

#870 fix(uui-radio): keyboard navigation does not work as intended
  packages/uui-radio/lib/uui-radio-group.element.ts
  packages/uui-radio/lib/uui-radio-group.test.ts
  packages/uui-radio/lib/uui-radio.element.ts
Labels: bug
