Repository umbraco/Umbraco.UI, pull requests merged in 2024-09, with the labels that each got.

#880 Story for input readonly
  packages/uui-input/lib/uui-input.story.ts
Labels: documentation, community/pr

#903 fix: Aligned more symbol to center
  packages/uui-symbol-more/lib/uui-symbol-more.element.ts
Labels: bug, community/pr

#913 Bugfix: Dropzone thinks custom file extensions are folders
  packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
  packages/uui-file-dropzone/lib/uui-file-dropzone.test.ts
Labels: bug

#918 Focus handle in slider instead of slider track itself
  packages/uui-slider/lib/uui-slider.element.ts
Labels: bug, community/pr
