Repository umbraco/Umbraco.UI, pull requests merged in 2025-08, with the labels that each got.

#1138 feat(uui-card): Adds checkbox for selection
  package-lock.json
  packages/uui-card-block-type/lib/uui-card-block-type.element.ts
  packages/uui-card-block-type/lib/uui-card-block-type.story.ts
  packages/uui-card-content-node/lib/uui-card-content-node.element.ts
  packages/uui-card-content-node/lib/uui-card-content-node.story.ts
  packages/uui-card-media/lib/uui-card-media.element.ts
  packages/uui-card-media/lib/uui-card-media.story.ts
  packages/uui-card-user/lib/uui-card-user.element.ts
  packages/uui-card-user/lib/uui-card-user.story.ts
  packages/uui-card/lib/uui-card.element.ts
  packages/uui-card/package.json
  packages/uui-card/tsconfig.json
Labels: feature

#1164 fix(uui-combobox): Remove bottom gap
  packages/uui-combobox/lib/uui-combobox.element.ts
Labels: bug

#1155 📝 Update Issue template link to new Umbraco forum
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, community/pr, ignore-for-release
