Repository umbraco/Umbraco.UI, pull requests merged in 2025-05, with the labels that each got.

#1084 Fix typo in comment
  packages/uui-button-copy-text/lib/uui-button-copy-text.element.ts
Labels: documentation, community/pr

#1075 Fix selection on click in color area
  packages/uui-base/lib/utils/drag.ts
Labels: bug, community/pr

#1021 feat: Specific input mode similar to input type
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-input/lib/uui-input.story.ts
Labels: feature, community/pr

#1060 fix: Text character length validation should be more helpful
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-textarea/lib/uui-textarea.element.ts
Labels: bug

#1069 feat: adds localization to uui-pagination
  packages/uui-pagination/lib/uui-pagination.element.ts
Labels: enhancement

#1076 Advanced color slider story
  packages/uui-color-slider/lib/uui-color-slider.element.ts
  packages/uui-color-slider/lib/uui-color-slider.story.ts
Labels: feature, community/pr

#1061 fix(uui-color-picker): alpha should default to 100 if there is no color string
  packages/uui-color-picker/lib/uui-color-picker.element.ts
  packages/uui-color-picker/lib/uui-color-picker.story.ts
Labels: bug

#1105 Fix: `uui-card-media`: flex-direction of "content"
  packages/uui-card-media/lib/uui-card-media.element.ts
  packages/uui-card-media/lib/uui-card-media.story.ts
Labels: bug

#1107 use firstUpdated for label feedback
  packages/uui-base/lib/mixins/LabelMixin.ts
Labels: bug
