Repository umbraco/Umbraco.UI, pull requests merged in 2025-03, with the labels that each got.

#1019 Rename id from slider to toggle
  packages/uui-toggle/lib/uui-toggle.element.ts
Labels: enhancement, community/pr

#1014 Fix: lower table cell height to take up less space
  packages/uui-table/lib/uui-table-cell.element.ts
Labels: bug

#1015 Fix: Readonly ref node padding
  packages/uui-ref-node/lib/uui-ref-node.element.ts
Labels: bug

#1010 Fix vertical alignment uui-symbol-expand.element.ts
  packages/uui-symbol-expand/lib/uui-symbol-expand.element.ts
Labels: bug, community/pr

#1025 More Symbol inheriting current color
  packages/uui-symbol-more/lib/uui-symbol-more.element.ts
Labels: bug

#1009 feat: New color 'invalid'
  packages/uui-action-bar/lib/uui-action-bar.story.ts
  packages/uui-badge/lib/uui-badge.element.ts
  packages/uui-badge/lib/uui-badge.story.ts
  packages/uui-base/lib/types/InterfaceColor.ts
  packages/uui-button/lib/uui-button.element.ts
  packages/uui-button/lib/uui-button.story.ts
  packages/uui-card/lib/uui-card.element.ts
  packages/uui-checkbox/lib/uui-checkbox.element.ts
  packages/uui-css/lib/custom-properties.story.ts
  packages/uui-css/lib/custom-properties/colors.css
  packages/uui-form-validation-message/lib/uui-form-validation-message.element.ts
  packages/uui-input/lib/uui-input.element.ts
  packages/uui-label/lib/uui-label.element.ts
  packages/uui-radio/lib/uui-radio-group.element.ts
  packages/uui-range-slider/lib/uui-range-slider.element.ts
  packages/uui-ref/lib/uui-ref.element.ts
  packages/uui-select/lib/uui-select.element.ts
  packages/uui-slider/lib/uui-slider.element.ts
  packages/uui-symbol-file-dropzone/lib/uui-symbol-file-dropzone.element.ts
  packages/uui-tag/lib/uui-tag.element.ts
  packages/uui-tag/lib/uui-tag.story.ts
  packages/uui-textarea/lib/uui-textarea.element.ts
  packages/uui-toast-notification/lib/uui-toast-notification.element.ts
  packages/uui-toast-notification/lib/uui-toast-notification.story.ts
  packages/uui-toggle/lib/uui-toggle.element.ts
Labels: feature

#985 feat: Adds uui-button-copy-text
  package-lock.json
  packages/uui-button-copy-text/README.md
  packages/uui-button-copy-text/lib/UUICopyTextEvent.ts
  packages/uui-button-copy-text/lib/index.ts
  packages/uui-button-copy-text/lib/uui-button-copy-text.element.ts
  packages/uui-button-copy-text/lib/uui-button-copy-text.story.ts
  packages/uui-button-copy-text/lib/uui-button-copy-text.test.ts
  packages/uui-button-copy-text/package.json
  packages/uui-button-copy-text/rollup.config.js
  packages/uui-button-copy-text/tsconfig.json
  packages/uui/lib/index.ts
Labels: feature, community/pr

#1038 Hotfix: Remove extra margin on ref-node (#1037)
  packages/uui-ref-node/lib/uui-ref-node.element.ts
Labels: bug

#1042 Fix bug long media name hides the thumbnail
  packages/uui-card-media/lib/uui-card-media.element.ts
Labels: bug

#1044 fix: ensure `renderSlots()` return correctly tagged unsafe html
  storyhelpers/render-slots.ts
Labels: bug

#1036 fix(uui-card): text overflow when user name is too long
  packages/uui-card-block-type/lib/uui-card-block-type.element.ts
  packages/uui-card-content-node/lib/uui-card-content-node.element.ts
  packages/uui-card-user/lib/uui-card-user.element.ts
  storyhelpers/render-slots.ts
Labels: bug
